---
tags: [rest, hateoas, hypermedia, security, testing, oauth]
projects: [spring-framework, spring-hateoas, spring-security, spring-security-oauth]

= Building REST Services with SpringBoot, H2, Angular and JPA


== Getting Started

Motivated by an interview assignment in building a Calendar/Schedule Event System, I will use this opportunity to create a Resource Booking System.

The phase of this project will be as such.

Phase I.
Establish Spring/JPA/Security Structure, and Spring MVC/Thyrmleaf/Bootstrap as AdminUI, Angular as General User UI, and possible Mobile frontend. 

SpringMVC.. as frontend.. searching..
1. There should be a minimum of two models consisting of a calendar (name, user) and calendar events (calendar, title, event date and time, location, attendee list, reminder time, and whether the reminder has been sent).
2. The app should expose a set of APIs to support the standard CRUD operations for calendar events.
3. Data access should be accomplished using anything other than raw SQL queries to the database (JPA, Hibernate, JDO, etc)
4. Implement APIs to allow a user to retrieve the list of events for a day, a week, or a month.
5. Implement a background service that sends out reminders based on the reminder time. Reminders can be printed to a log file or the console for this purpose.
6. Implement user authentication using a token based mechanism of your choice so that users can only create/update/delete their own calendar events.
7. Provide sample commands to retrieve a list of all events, a day/week/month's events, and for updating, deleting,  and creating new events, (curl, python script, java program, etc.).

If you implement #6, provide instructions on setting up a default user so that we are able to login to your application




Phase II.
Establish User and Basic login info
Establish Calendar/Schedule using Angular and Springboot Microservice..etc.
Establish Google Map Service in identifying hotel location, or nearby location searching, this will later on be integrated to Mobile App.

Phase III.
Establish more business Entity as Hotel, Rooms, and Services.
Provide a self functional site to admin, booking and maintain their data, etc..
Any User can upload their room or hotel info, and any user can see the room info..
...

Phase IV.
Integrate with third party pay system.
Integrate with file process system through own or Spring batch system...
Integrate with Ofbiz systems to make it a complete ERP system on Spring..

Phase VI.
There just so.. so many opportunities there, and so many can do..  
God know where it goes.. wish me luck!



