---
tags: [rest, hateoas, hypermedia, security, testing, oauth]
projects: [spring-framework, spring-hateoas, spring-security, spring-security-oauth]

= Building REST Services with SpringBoot, H2, Angular and JPA


== Getting Started

Motivated by an interview assignment in building a Calendar/Schedule Event System, I will use this opportunity to create a Resource Booking System.

The phase of this project will be as such.

Phase I.
Establish Spring/JPA/Security Structure, and Spring MVC as AdminUI, Angular as General User UI, and possible Mobile frontend. 

Phase II.
Establish User and Basic login info
Establish Calendar/Schedule using Angular and Springboot Microservice..etc.
Establish Google Map Service in identifying hotel location, or nearby location searching, this will later on be integrated to Mobile App.

Phase III.
Establish more business Entity as Hotel, Rooms, and Services.
Provide a self functional site to admin, booking and maintain their data, etc..
Any User can upload their room or hotel info, and any user can see the room info..
...

Phase IV.
Integrate with third party pay system.
Integrate with file process system through own or Spring batch system...
Integrate with Ofbiz systems to make it a complete ERP system on Spring..

Phase VI.
There just so.. so many opportunities there, and so many can do..  if you have money to vest not to waste, put on this project, I have skills and experiences, we should have good journey. 

God know where it goes.. wish me luck!



